In [1]:
import pandas as pd

from headers import *
from training_helper import trainPipeline
from utils.custom_train_test_split import *
from joblib import dump, load
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from numpy import mean

In [4]:
cutoffs = [0.10, 0.15, 0.20]
files = ['../data/deduplicated/combined_inner_ticker.csv']
thresholds = [90, 95]
# yLabels = ['alpha1Year', 'alpha2Year']
yLabels = ['alpha1Year']
modelKeys = ['svc', 'tree']

In [5]:
trainDf, testDf = per_year_train_test_split(files, format='%Y-%m-%d')
X_train = trainDf[ratioKeys + relativeRatioKeys]
X_test = testDf[ratioKeys + relativeRatioKeys]

In [12]:
cutoffs = [0.0, 0.10, 0.15, 0.20, 0.35]
modelKeys = ['svc',]
trainPipeline(cutoffs, yLabels, trainDf, testDf, thresholds, saveModel=True, isBalanced=True)

-----------------
% of True in dataset 50.92% resulted in 24.61% and median 17.28%
MODEL tree
For alpha1Year, yCutoff = 0.0, taken used - 4975 is 47.13%
Mean was 4.92%, median was 1.81%
MODEL svc
For alpha1Year, yCutoff = 0.0, taken used - 4810 is 45.57%
Mean was 4.8%, median was 1.19%
% of True taken with threshold 90 adjustment -  1056
For threshold data - mean was 7.81%, median was 1.38%
% of True taken with threshold 95 adjustment -  528
For threshold data - mean was 3.48%, median was -2.29%
-----------------
-----------------
% of True in dataset 35.23% resulted in 33.35% and median 25.45%
MODEL tree
For alpha1Year, yCutoff = 0.1, taken used - 3475 is 32.92%
Mean was 6.23%, median was 2.06%
MODEL svc
For alpha1Year, yCutoff = 0.1, taken used - 4988 is 47.25%
Mean was 4.75%, median was 1.31%
% of True taken with threshold 90 adjustment -  1056
For threshold data - mean was 7.15%, median was 0.87%
% of True taken with threshold 95 adjustment -  528
For threshold data - mean was 6.35

{'alpha1Year': {'tree': [{'mean': np.float64(0.04918178930199273),
    'median': np.float64(0.0181092795664793),
    'taken': np.int64(4975)},
   {'mean': np.float64(0.06227801049402202),
    'median': np.float64(0.0206069183571782),
    'taken': np.int64(3475)},
   {'mean': np.float64(0.06557951406604919),
    'median': np.float64(0.012687612194422049),
    'taken': np.int64(2884)},
   {'mean': np.float64(0.06210107925665286),
    'median': np.float64(0.0084456281149317),
    'taken': np.int64(2491)},
   {'mean': np.float64(0.09700395197842221),
    'median': np.float64(0.03338911586501295),
    'taken': np.int64(1184)}],
  'svc': [{'mean': np.float64(0.048025976308212856),
    'median': np.float64(0.011923310892604299),
    'taken': np.int64(4810)},
   {'mean': np.float64(0.04747311462341424),
    'median': np.float64(0.01314019390909185),
    'taken': np.int64(4988)},
   {'mean': np.float64(0.049200691614255075),
    'median': np.float64(0.0162187919389906),
    'taken': np.int64(49

In [4]:
# trainPipeline(cutoffs, yLabels, trainDf, testDf, thresholds, saveModel=True)

-----------------
% of True in dataset 35.23% resulted in 33.35% and median 25.45%
MODEL tree
For alpha1Year, yCutoff = 0.1, taken used - 3602 is 34.12%
Mean was 6.04%, median was 2.27%
MODEL svc
For alpha1Year, yCutoff = 0.1, taken used - 19 is 0.18%
Mean was 5.73%, median was -1.89%
% of True taken with threshold 90 adjustment -  1056
For threshold data - mean was 7.47%, median was 1.82%
% of True taken with threshold 95 adjustment -  528
For threshold data - mean was 7.62%, median was 3.64%
-----------------
-----------------
% of True in dataset 28.24% resulted in 38.53% and median 29.9%
MODEL tree
For alpha1Year, yCutoff = 0.15, taken used - 3114 is 29.5%
Mean was 5.69%, median was 1.17%
MODEL svc
For alpha1Year, yCutoff = 0.15, taken used - 9 is 0.09%
Mean was 9.79%, median was -13.9%
% of True taken with threshold 90 adjustment -  1056
For threshold data - mean was 8.49%, median was 2.68%
% of True taken with threshold 95 adjustment -  528
For threshold data - mean was 8.01%, me

{'alpha1Year': {'tree': [{'mean': np.float64(0.06036016084213012),
    'median': np.float64(0.02272711924272555),
    'taken': np.int64(3602)},
   {'mean': np.float64(0.056872310887688966),
    'median': np.float64(0.01172876676442605),
    'taken': np.int64(3114)},
   {'mean': np.float64(0.052522327238327386),
    'median': np.float64(0.01395581407404505),
    'taken': np.int64(2572)}],
  'svc': [{'mean': np.float64(0.05725471820444397),
    'median': np.float64(-0.0189153230747683),
    'taken': np.int64(19)},
   {'mean': np.float64(0.09791089394438221),
    'median': np.float64(-0.1389913260393867),
    'taken': np.int64(9)},
   {'mean': np.float64(0.5890923759435145),
    'median': np.float64(0.8006267657160063),
    'taken': np.int64(3)}],
  'svcThreshold90': [{'mean': np.float64(0.0746767941267405),
    'median': np.float64(0.0182337097483905),
    'taken': -1},
   {'mean': np.float64(0.0849160674624662),
    'median': np.float64(0.0268083570377613),
    'taken': -1},
   {'mean':

In [5]:
noSpecReturns = []
diffs = []
for modelKey in modelKeys:
    for yLabel in yLabels:
        print('========')
        for cutoff in cutoffs:
            print(f'{modelKey} - {yLabel} - {cutoff}')
            grid = load(f'../data/cvPipeline-2/{modelKey}{yLabel}{cutoff}.joblib')
            y_pred = grid.predict(X_test)
            y_true = np.where(testDf[yLabel] <= cutoff, 0, 1)
            print(confusion_matrix(y_true, y_pred))
            print(classification_report(y_true, y_pred))
            xTaken = X_test[y_pred == 1]
            takenData = testDf.loc[testDf.index.intersection(xTaken.index)]
            print(f'Overall mean was {round(takenData.loc[:, yLabel].mean() * 100,2)}%')

            if modelKey != 'svc':
                continue
            model = grid.best_estimator_['svc']
            scaler = grid.best_estimator_['scaler']
            X_scaled = scaler.transform(X_test)
            scores = model.decision_function(X_scaled)
            for threshold in thresholds:
                barrier = np.percentile(scores, threshold)
                y_pred_threshold = scores >= barrier
                xTakenThreshold = X_test[y_pred_threshold]
                takenDataThreshold = testDf.loc[testDf.index.intersection(xTakenThreshold.index)]
                print(
                    f'For threshold {threshold} data - mean was {round(takenDataThreshold.loc[:, yLabel].mean() * 100, 2)}%')
                thresholdLabel = f'svcThreshold{threshold}'
                print(confusion_matrix(y_true, y_pred_threshold))
                print(classification_report(y_true, y_pred_threshold))

                returns = takenDataThreshold[yLabel]
                bins = pd.cut(returns, bins=[-1.0, -0.6, -0.3, -0.1, 0.1, 0.3, 0.6, 1.0, 10])
                bin_counts = bins.value_counts().sort_index()
                bin_df = bin_counts.reset_index()
                bin_df.columns = ['Bin Range', 'Count']
                print(bin_df)
                noSpecialReturns = mean(returns[returns < 1.0])
                noSpecReturns.append(noSpecialReturns)
                print(f'Without 100+% returns mean was {noSpecialReturns}.')
                diff = mean(returns) - noSpecialReturns
                diffs.append(diff)
                print(f'Generated diff = {diff}')
                print('--------')


svc - alpha1Year - 0.1
[[6824   13]
 [3713    6]]
              precision    recall  f1-score   support

           0       0.65      1.00      0.79      6837
           1       0.32      0.00      0.00      3719

    accuracy                           0.65     10556
   macro avg       0.48      0.50      0.39     10556
weighted avg       0.53      0.65      0.51     10556

Overall mean was 5.73%
For threshold 90 data - mean was 7.47%
[[6191  646]
 [3309  410]]
              precision    recall  f1-score   support

           0       0.65      0.91      0.76      6837
           1       0.39      0.11      0.17      3719

    accuracy                           0.63     10556
   macro avg       0.52      0.51      0.46     10556
weighted avg       0.56      0.63      0.55     10556

      Bin Range  Count
0  (-1.0, -0.6]      5
1  (-0.6, -0.3]     93
2  (-0.3, -0.1]    253
3   (-0.1, 0.1]    295
4    (0.1, 0.3]    211
5    (0.3, 0.6]    140
6    (0.6, 1.0]     39
7   (1.0, 10.0]     20


In [6]:
print(mean(noSpecReturns))
print(mean(diffs))

0.018329605630572895
0.1561246343978376


Kompletne zniszczenie 2y returns

In [7]:
print(diffs)

[np.float64(0.038392496858124334), np.float64(0.03449594393848685), np.float64(0.03657574291112117), np.float64(0.029746088633546844), np.float64(0.029149685788108483), np.float64(0.03509732324508082), np.float64(0.24182026932799922), np.float64(0.3216883608520682), np.float64(0.2469447126370399), np.float64(0.3128643196700065), np.float64(0.22996465219661455), np.float64(0.31675601671585474)]


TO SAMO TYLKO DLA BALANCED

In [17]:
noSpecReturns = []
diffs = []
for modelKey in modelKeys:
    for yLabel in yLabels:
        print('========')
        for cutoff in cutoffs:
            print(f'{modelKey} - {yLabel} - {cutoff}')
            grid = load(f'../data/cvPipeline-2/balanced/{modelKey}{yLabel}{cutoff}.joblib')
            y_pred = grid.predict(X_test)
            y_true = np.where(testDf[yLabel] <= cutoff, 0, 1)
            print(confusion_matrix(y_true, y_pred))
            print(classification_report(y_true, y_pred))
            xTaken = X_test[y_pred == 1]
            takenData = testDf.loc[testDf.index.intersection(xTaken.index)]
            print(f'Overall mean was {round(takenData.loc[:, yLabel].mean() * 100,2)}%')
            returns = takenData[yLabel]
            bins = pd.cut(returns, bins=[-1.0, -0.6, -0.3, -0.1, 0.1, 0.3, 0.6, 1.0, 10])
            bin_counts = bins.value_counts().sort_index()
            bin_df = bin_counts.reset_index()
            bin_df.columns = ['Bin Range', 'Count']
            print(bin_df)

            if modelKey != 'svc':
                continue
            model = grid.best_estimator_['svc']
            scaler = grid.best_estimator_['scaler']
            X_scaled = scaler.transform(X_test)
            scores = model.decision_function(X_scaled)
            for threshold in thresholds:
                barrier = np.percentile(scores, threshold)
                y_pred_threshold = scores >= barrier
                xTakenThreshold = X_test[y_pred_threshold]
                takenDataThreshold = testDf.loc[testDf.index.intersection(xTakenThreshold.index)]
                print(
                    f'For threshold {threshold} data - mean was {round(takenDataThreshold.loc[:, yLabel].mean() * 100, 2)}%')
                thresholdLabel = f'svcThreshold{threshold}'
                print(confusion_matrix(y_true, y_pred_threshold))
                print(classification_report(y_true, y_pred_threshold))

                returns = takenDataThreshold[yLabel]
                bins = pd.cut(returns, bins=[-1.0, -0.6, -0.3, -0.1, 0.1, 0.3, 0.6, 1.0, 10])
                bin_counts = bins.value_counts().sort_index()
                bin_df = bin_counts.reset_index()
                bin_df.columns = ['Bin Range', 'Count']
                print(bin_df)
                noSpecialReturns = mean(returns[returns < 1.0])
                noSpecReturns.append(noSpecialReturns)
                print(f'Without 100+% returns mean was {noSpecialReturns}.')
                diff = mean(returns) - noSpecialReturns
                diffs.append(diff)
                print(f'Generated diff = {diff}')
                print('--------')


svc - alpha1Year - 0.0
[[2864 2317]
 [2882 2493]]
              precision    recall  f1-score   support

           0       0.50      0.55      0.52      5181
           1       0.52      0.46      0.49      5375

    accuracy                           0.51     10556
   macro avg       0.51      0.51      0.51     10556
weighted avg       0.51      0.51      0.51     10556

Overall mean was 4.8%
      Bin Range  Count
0  (-1.0, -0.6]     27
1  (-0.6, -0.3]    390
2  (-0.3, -0.1]   1156
3   (-0.1, 0.1]   1506
4    (0.1, 0.3]    987
5    (0.3, 0.6]    549
6    (0.6, 1.0]    134
7   (1.0, 10.0]     61
For threshold 90 data - mean was 7.81%
[[4673  508]
 [4827  548]]
              precision    recall  f1-score   support

           0       0.49      0.90      0.64      5181
           1       0.52      0.10      0.17      5375

    accuracy                           0.49     10556
   macro avg       0.51      0.50      0.40     10556
weighted avg       0.51      0.49      0.40     10556

 

In [14]:
3 + 43 + 107 + 140 + 127 + 75 + 20 + 13

528

In [15]:
443+85

528